### ISSUE TITLE
Keras Model Neuron Compile Error

### ISSUE THREAD

**Issue by fishuke** [aws/aws-neuron-sdk#455]
```
2022-07-27 14:30:11.211885: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-07-27 14:30:11.211926: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ip-12-0-11-93): /proc/driver/nvidia/version does not exist
2022-07-27 14:30:11.406435: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING:tensorflow:SavedModel saved prior to TF 2.5 detected when loading Keras model. Please ensure that you are saving the model with model.save() or tf.keras.models.save_model(), *NOT* tf.saved_model.save(). To confirm, there should be a file named "keras_metadata.pb" in the SavedModel directory.
Traceback (most recent call last):
  File "compiler.py", line 13, in <module>
    example_inputs = tf.random.uniform([None, 256, 256, 3])
  File "/home/ubuntu/tensorflow_venv/lib/python3.7/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/ubuntu/tensorflow_venv/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 106, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: Attempt to convert a value (None) with an unsupported type (<class 'NoneType'>) to a Tensor.
```

Hello I'm trying to compile a keras model into neuron. I am getting this error.

```
import os
import tensorflow as tf
import tensorflow.neuron as tfn
from tensorflow.keras.models import load_model

WORKSPACE = './models'
os.makedirs(WORKSPACE, exist_ok=True)
model_dir = os.path.join(WORKSPACE)

input0 = tf.keras.layers.Input(3)
dense0 = tf.keras.layers.Dense(3)(input0)
model = load_model(model_dir)
example_inputs = tf.random.uniform([None, 256, 256, 3])
model_neuron = tfn.trace(model, example_inputs)  # trace

model_dir = './model_neuron'
model_neuron.save(model_dir)
```

What is the problem here?

**Comment by aws-joshim** [comment]
@fishuke we are looking into this. Can you share the version of tensorflow that you are using for your test above?

**Comment by aws-joshim** [comment]
@fishuke, your compilation error is caused by the incorrect invocation of the tf.random.uniform API. Reference to the TF documentation is at https://www.tensorflow.org/api_docs/python/tf/random/uniform

**Comment by fishuke** [comment]
Hello thanks for your response I fixed the mistake with replacing this line:
`example_inputs = tf.random.uniform([None, 256, 256, 3])`
`example_inputs = tf.random.uniform([1, 256, 256, 3])`

Now i have the following errors:

```bash
2022-07-28 07:31:46.183641: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-07-28 07:31:46.183694: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ip-12-0-11-93): /proc/driver/nvidia/version does not exist
2022-07-28 07:31:46.400486: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING:tensorflow:SavedModel saved prior to TF 2.5 detected when loading Keras model. Please ensure that you are saving the model with model.save() or tf.keras.models.save_model(), *NOT* tf.saved_model.save(). To confirm, there should be a file named "keras_metadata.pb" in the SavedModel directory.
2022-07-28 07:32:15.400821: I tensorflow/core/grappler/devices.cc:66] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-07-28 07:32:15.400993: I tensorflow/core/grappler/clusters/single_machine.cc:358] Starting new session
2022-07-28 07:32:19.216936: I tensorflow/core/grappler/devices.cc:66] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-07-28 07:32:19.217071: I tensorflow/core/grappler/clusters/single_machine.cc:358] Starting new session
2022-07-28 07:32:19.749698: I tensorflow/neuron/grappler/convert/segment.cc:456] There are 9 ops of 6 different types in the graph that are not compiled by neuron-cc: Pad, AddV2, Mul, Placeholder, NoOp, Const, (For more information see https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/neuron-cc-ops/neuron-cc-ops-tensorflow.html).
2022-07-28 07:32:20.765657: I tensorflow/core/grappler/devices.cc:66] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-07-28 07:32:20.765778: I tensorflow/core/grappler/clusters/single_machine.cc:358] Starting new session
2022-07-28 07:32:23.057602: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-07-28 07:32:23.122552: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:237] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
.
Compiler status ERROR
WARNING:tensorflow:neuron-cc failed with:
2022-07-28 07:32:31.120319: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-07-28 07:32:31.120394: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ip-12-0-11-93): /proc/driver/nvidia/version does not exist
07/28/2022 07:32:32 AM ERROR 8619 [neuron-cc]: ***************************************************************
07/28/2022 07:32:32 AM ERROR 8619 [neuron-cc]:  An Internal Compiler Error has occurred
07/28/2022 07:32:32 AM ERROR 8619 [neuron-cc]: ***************************************************************
07/28/2022 07:32:32 AM ERROR 8619 [neuron-cc]:
07/28/2022 07:32:32 AM ERROR 8619 [neuron-cc]: Error message:  ERROR: Failed in  /home/ubuntu/tensorflow_venv/lib/python3.7/site-packages/neuroncc/starfish/bin/hlo2penguin --input /tmp/tmpwmyfozib/hlo_module.pb --out-dir ./ --output penguin.py --disable-load-fusion
07/28/2022 07:32:32 AM ERROR 8619 [neuron-cc]:
07/28/2022 07:32:32 AM ERROR 8619 [neuron-cc]: Error class:    AssertionError
07/28/2022 07:32:32 AM ERROR 8619 [neuron-cc]: Error location: Unknown
07/28/2022 07:32:32 AM ERROR 8619 [neuron-cc]: Command line:   /home/ubuntu/tensorflow_venv/bin/neuron-cc compile /tmp/tmpwmyfozib/hlo_module.pb --framework XLA --pipeline compile SaveTemps --output /tmp/tmpwmyfozib/hlo_module.neff --verbose=35 --fast-math=none --fp32-cast=matmult-fp16 --enable-fast-context-switch
07/28/2022 07:32:32 AM ERROR 8619 [neuron-cc]:
07/28/2022 07:32:32 AM ERROR 8619 [neuron-cc]: Internal details:
07/28/2022 07:32:32 AM ERROR 8619 [neuron-cc]:   File "neuroncc/driver/CommandDriver.py", line 223, in neuroncc.driver.CommandDriver.CommandDriver.run
07/28/2022 07:32:32 AM ERROR 8619 [neuron-cc]:   File "neuroncc/driver/commands/CompileCommand.py", line 525, in neuroncc.driver.commands.CompileCommand.CompileCommand.run
07/28/2022 07:32:32 AM ERROR 8619 [neuron-cc]:   File "neuroncc/driver/Job.py", line 289, in neuroncc.driver.Job.SingleInputJob.run
07/28/2022 07:32:32 AM ERROR 8619 [neuron-cc]:   File "neuroncc/driver/Pipeline.py", line 30, in neuroncc.driver.Pipeline.Pipeline.runSingleInput
07/28/2022 07:32:32 AM ERROR 8619 [neuron-cc]:   File "neuroncc/driver/Job.py", line 289, in neuroncc.driver.Job.SingleInputJob.run
07/28/2022 07:32:32 AM ERROR 8619 [neuron-cc]:   File "neuroncc/driver/Pipeline.py", line 30, in neuroncc.driver.Pipeline.Pipeline.runSingleInput
07/28/2022 07:32:32 AM ERROR 8619 [neuron-cc]:   File "neuroncc/driver/Job.py", line 289, in neuroncc.driver.Job.SingleInputJob.run
07/28/2022 07:32:32 AM ERROR 8619 [neuron-cc]:   File "neuroncc/driver/jobs/Frontend.py", line 425, in neuroncc.driver.jobs.Frontend.Frontend.runSingleInput
07/28/2022 07:32:32 AM ERROR 8619 [neuron-cc]:   File "neuroncc/driver/jobs/Frontend.py", line 225, in neuroncc.driver.jobs.Frontend.Frontend.runXLAFrontend
07/28/2022 07:32:32 AM ERROR 8619 [neuron-cc]:
07/28/2022 07:32:32 AM ERROR 8619 [neuron-cc]: Version information:
07/28/2022 07:32:32 AM ERROR 8619 [neuron-cc]:   Neuron Compiler version 1.9.1.0+5f09e5c8e
07/28/2022 07:32:32 AM ERROR 8619 [neuron-cc]:
07/28/2022 07:32:32 AM ERROR 8619 [neuron-cc]:   HWM version 1.9.0.0-0
07/28/2022 07:32:32 AM ERROR 8619 [neuron-cc]:   NEFF version Dynamic
07/28/2022 07:32:32 AM ERROR 8619 [neuron-cc]:   TVM version 1.9.1.0+0
07/28/2022 07:32:32 AM ERROR 8619 [neuron-cc]:   NumPy version 1.20.0
07/28/2022 07:32:32 AM ERROR 8619 [neuron-cc]:   MXNet not available
07/28/2022 07:32:32 AM ERROR 8619 [neuron-cc]:   TF not available
07/28/2022 07:32:32 AM ERROR 8619 [neuron-cc]:
07/28/2022 07:32:32 AM ERROR 8619 [neuron-cc]: Artifacts stored in: /tmp/tmpwmyfozib

WARNING:tensorflow:
################### Attention!!! ###################
According to semantic analysis, this model requires
a neuron-cc 1.3 based fall-back code generator.
####################################################
WARNING:tensorflow:
################### Attention!!! ###################
According to semantic analysis, this model requires
a neuron-cc 1.3 based fall-back code generator.
####################################################

```

**Comment by fishuke** [comment]
With Neuron Compiler version 1.11.4.0 

```bash
2022-07-28 07:24:10.620360: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-07-28 07:24:10.620415: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ip-12-0-11-93): /proc/driver/nvidia/version does not exist
2022-07-28 07:24:10.835568: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING:tensorflow:SavedModel saved prior to TF 2.5 detected when loading Keras model. Please ensure that you are saving the model with model.save() or tf.keras.models.save_model(), *NOT* tf.saved_model.save(). To confirm, there should be a file named "keras_metadata.pb" in the SavedModel directory.
2022-07-28 07:24:39.958839: I tensorflow/core/grappler/devices.cc:66] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-07-28 07:24:39.958998: I tensorflow/core/grappler/clusters/single_machine.cc:358] Starting new session
2022-07-28 07:24:43.778619: I tensorflow/core/grappler/devices.cc:66] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-07-28 07:24:43.778759: I tensorflow/core/grappler/clusters/single_machine.cc:358] Starting new session
2022-07-28 07:24:44.311025: I tensorflow/neuron/grappler/convert/segment.cc:456] There are 9 ops of 6 different types in the graph that are not compiled by neuron-cc: Pad, AddV2, Mul, Placeholder, NoOp, Const, (For more information see https://awsdocs-neuron.readthedocs-hosted.com/en/latest/release-notes/neuron-cc-ops/neuron-cc-ops-tensorflow.html).
2022-07-28 07:24:45.329696: I tensorflow/core/grappler/devices.cc:66] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0
2022-07-28 07:24:45.329830: I tensorflow/core/grappler/clusters/single_machine.cc:358] Starting new session
2022-07-28 07:24:47.566641: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-07-28 07:24:47.639998: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:237] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
........
Compiler status ERROR
WARNING:tensorflow:neuron-cc failed with:
2022-07-28 07:24:55.689049: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-07-28 07:24:55.689120: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (ip-12-0-11-93): /proc/driver/nvidia/version does not exist
07/28/2022 07:27:19 AM ERROR 8340 [ILPOpt]: SB tensor overflow: TongaSB[None + 0, None + 0 * 4260096](1,)(1,) partitions[0] float32 %24196[1, 1065024]
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]: ***************************************************************
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:  An Internal Compiler Error has occurred
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]: ***************************************************************
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]: Error message:  Incorrect IR by <class 'neuroncc.starfish.penguin.targets.tonga.passes.VectorizeLoop.VectorizeLoop'>
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]: Error class:    AssertionError
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]: Error location: Unknown
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]: Command line:   /home/ubuntu/tensorflow_venv/bin/neuron-cc compile /tmp/tmp7sdl4bw9/hlo_module.pb --framework XLA --pipeline compile SaveTemps --output /tmp/tmp7sdl4bw9/hlo_module.neff --verbose=35 --fast-math=none --fp32-cast=matmult-fp16 --enable-fast-context-switch
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]: Internal details:
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:   File "neuroncc/driver/CommandDriver.py", line 224, in neuroncc.driver.CommandDriver.CommandDriver.run
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:   File "neuroncc/driver/commands/CompileCommand.py", line 551, in neuroncc.driver.commands.CompileCommand.CompileCommand.run
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:   File "neuroncc/driver/commands/CompileCommand.py", line 529, in neuroncc.driver.commands.CompileCommand.CompileCommand.runPipeline
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:   File "neuroncc/driver/commands/CompileCommand.py", line 533, in neuroncc.driver.commands.CompileCommand.CompileCommand.runPipeline
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:   File "neuroncc/driver/Job.py", line 289, in neuroncc.driver.Job.SingleInputJob.run
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:   File "neuroncc/driver/Pipeline.py", line 30, in neuroncc.driver.Pipeline.Pipeline.runSingleInput
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:   File "neuroncc/driver/Job.py", line 289, in neuroncc.driver.Job.SingleInputJob.run
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:   File "neuroncc/driver/Pipeline.py", line 30, in neuroncc.driver.Pipeline.Pipeline.runSingleInput
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:   File "neuroncc/driver/Job.py", line 289, in neuroncc.driver.Job.SingleInputJob.run
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:   File "neuroncc/driver/jobs/Frontend.py", line 425, in neuroncc.driver.jobs.Frontend.Frontend.runSingleInput
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:   File "neuroncc/driver/jobs/Frontend.py", line 238, in neuroncc.driver.jobs.Frontend.Frontend.runXLAFrontend
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:   File "neuroncc/starfish/penguin/Frontend.py", line 109, in neuroncc.starfish.penguin.Frontend.tensorizeXla
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:   File "neuroncc/starfish/penguin/Frontend.py", line 110, in neuroncc.starfish.penguin.Frontend.tensorizeXla
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:   File "neuroncc/starfish/penguin/Frontend.py", line 127, in neuroncc.starfish.penguin.Frontend.tensorizeXla
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:   File "neuroncc/starfish/penguin/Compile.py", line 241, in neuroncc.starfish.penguin.Compile.compile_cu
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 380, in neuroncc.starfish.penguin.DotTransform.PassManager.transformFunction
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 134, in neuroncc.starfish.penguin.DotTransform.DotTransform.run_or_rollback
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 178, in neuroncc.starfish.penguin.DotTransform.DotTransform.run_with_exception_handling
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 160, in neuroncc.starfish.penguin.DotTransform.DotTransform.run_with_exception_handling
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 186, in neuroncc.starfish.penguin.DotTransform.DotTransform.timed_run_
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 188, in neuroncc.starfish.penguin.DotTransform.DotTransform.timed_run_
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 189, in neuroncc.starfish.penguin.DotTransform.DotTransform.timed_run_
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 206, in neuroncc.starfish.penguin.DotTransform.DotTransform.run_
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 207, in neuroncc.starfish.penguin.DotTransform.DotTransform.run_
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 287, in neuroncc.starfish.penguin.DotTransform.DotTransform.transformFunction
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 281, in neuroncc.starfish.penguin.DotTransform.DotTransform.runTransforms
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:   File "neuroncc/starfish/penguin/targets/tonga/passes/ILPOpt.py", line 42, in neuroncc.starfish.penguin.targets.tonga.passes.ILPOpt.ILPOpt.transformStmts
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 348, in neuroncc.starfish.penguin.DotTransform.IterativeTransform.iterate
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:   File "neuroncc/starfish/penguin/DotTransform.py", line 289, in neuroncc.starfish.penguin.DotTransform.DotTransform.transformFunction
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:   File "neuroncc/starfish/penguin/targets/tonga/Tonga.py", line 353, in neuroncc.starfish.penguin.targets.tonga.Tonga.IterativeTongaLowering.verify
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]: Version information:
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:   Neuron Compiler version 1.11.4.0+97f99abe4
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:   HWM version 1.11.0.0-0
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:   NEFF version Dynamic
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:   TVM version 1.11.0.0+0
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:   NumPy version 1.20.0
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:   MXNet not available
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:   TF not available
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]:
07/28/2022 07:27:19 AM ERROR 8340 [neuron-cc]: Artifacts stored in: /tmp/tmp7sdl4bw9

WARNING:tensorflow:
################### Attention!!! ###################
According to semantic analysis, this model requires
a neuron-cc 1.3 based fall-back code generator.
####################################################
WARNING:tensorflow:
################### Attention!!! ###################
According to semantic analysis, this model requires
a neuron-cc 1.3 based fall-back code generator.
####################################################
```

**Comment by fishuke** [comment]
@aws-joshim

**Comment by aws-joshim** [comment]
@fishuke the compilation error that you encountered with the 1.11.4.0 compiler version is most likely a result of operations that are not supported for the Tensorflow 2.x version of Neuron. If you are able to share a public reference to the model , we can look into the compilation error and future roadmap support

**Comment by fishuke** [comment]
I can give two examples of old repositories that is used by a lot of people:

https://github.com/notAI-tech/NudeNet
https://github.com/faustomorales/keras-ocr

**Comment by aws-taylor** [comment]
Hello @fishuke,

  Are you able to share more precise steps to reproduce, especially with regards to the dependency versions you're using. Performing `pip freeze` would be helpful. Unfortunately many of these deep learning and numeric frameworks and the dependencies thereof are extremely sensitive to versions, and this is true of both NudeNet and keras-ocr. Without more information it is difficult to reproduce your error.

-Taylor
